version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: twitter-trends-batch.app
    volumes:
      - ./app:/app
    tty:
      true
  postgres:
    image: postgres:14.3
    container_name: twitter-trends-batch.postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: twitter_trends
    ports:
      - 5432:5432 
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  postgres-test:
    image: postgres:14.3
    container_name: twitter-trends-batch.postgres-test
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: twitter_trends
    ports:
      - 54321:5432 
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d