version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2022.04.1
    step:
      - checkout
      - run:
          name: Create .env file
          command: | 
            echo $TEST_ENV | base64 -di > ./app/.env
      - run:
          name: Build App Container
          command: | 
            docker-compose build app
      - run:
          name: Run Docker Compose
          command: |
            docker-compose up -d
      - run:
          name: Run App Test
          command: | 
            docker-compose exec -T app pytest

workflows:
  Build-And-Test:
    jobs: 
      - build-and-test
