name: CI

on:
  push:
    branches: ["feature/github_actions"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout docker repositoy
        uses: actions/checkout@v3
        with:
          repository: 44taka/twitter-trends-docker
      - name: Check Directory
        run: ls -la
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
