name: CI

on:
  push:
    branches: ["feature/github_actions"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app container
        run: docker-compose build app
      - name: docker-compose up
        run: docker-compose up
      - name: Run test
        run: docker-compose exec app pytest
